baseURL = "http://example.org/"
languageCode = "en-us"
title = "ShannonWadi"
theme = "alpha-church"

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
      name = "Services"
      url = "/about"
      weight = 2

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

  [[menu.main]]
    name = "Gallery"
    url = "#"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5

# Paramaters for the whole site
[params]
  title = "ShannonWadi"
  subtitle = "Location Waterfront"
  author = ""
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp
  logo = "logo.png"
  customCSS = ["example.css"]

  [params.banner]
    image = "img/banner.jpg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

  #[params.podcast]
  #  title = "Listen to Alpha Church"
  #  subtitle = ""
  #  summary = "Alpha-Church sermons, talks, messages—podcasted."
  #  email = "test@example.com"
  #  copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
  #  image = "img/podcast-cover.jpg"
  #  category = "Religion & Spirituality"
  #  sub_category = "Christianity"
  #  iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
  #  feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"

  [params.map]
    #service = "google" #"osm" for OpenStreetMaps, "google" for Google Maps, or "mapbox" for Mapbox, see SETUP.md
    # For Open Street Map widgets
    latitude = "19.245588"
    longitude = "72.782039"
    zoom = "18"
    # If you want to use google maps you'll need an API Key from Google https://developers.google.com/maps/documentation/embed/get-api-key
    service = "osm"
    api_key = "AIzaSyAKHZusXCfv48XCt7sg31qfan3kA11JJqE"
    #language = "fr" #Optional
    #region = "FR" #Optional

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify", "formspree" or "php"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or else users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    #
    #If you use php, you need to host this site on a Server capable of running php.
    # Please edit the /static/contact_mail.php file from the exampleSite.
    #service = "netlify"
    #confirm_page = "/contact_thanks"
    # formspree_email=""


    [params.footer]
      copyright = ["Developed By : [GreyNimbus](//greynimbus.com)"
                  ]

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/"

    [[params.links]]
      service = "Instagram"
      icon = "fa-instagram"
      icon_pack = "fab"
      link = "//instagram.com/"

    [[params.links]]
        service = "Youtube"
        icon = "fa-youtube"
        icon_pack = "fab"
        link = "//youtube.com/"
