################################# Default configuration ###################
baseURL = "https://shannonwadi.github.io"
title = "Shannon Wadi"
subtitle= "Location Waterfront"
publishDir="docs"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "Shannonwadi_logo_full_width.png"
logo_width = "250px"

# Meta data
description = "This is meta description"
author = "GreyNimbus"
# Contact Information
mobile = "+91 91366 22218"
email = "shannonwadi@gmail.com"
location = "Shannon wadi, Gorai Beach, Gorai Village, Borivali (W), Mumbai: 400091"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

color_theme = "default"
# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "19.245588"
map_longitude =  "72.782039"
map_marker = "images/marker.png"


############################# social site ########################
[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-youtube-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 [GreyNimbus](https://www.greynimbus.com) All Rights Reserved"

################################ Contact Info ########################
[[params.contact]]
contacttype = "email"
text = "shannonwadi@gmail.com"

[[params.contact]]
contacttype = "phone"
text = "+91 91366 22218"

##############menu######################
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
      name = "Services"
      url = "/service"
      weight = 2

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
  [[menu.main]]
    name = "Gallery"
    url = "/gallery"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5
######################### english navigation #############################
# main menu
# [[Languages.en.menu.main]]
# name = "Home"
# URL = "/"
# weight = 1
#
# [[Languages.en.menu.main]]
# name = "About"
# URL = "about"
# weight = 2
#
# [[Languages.en.menu.main]]
# name = "Project"
# URL = "project"
# weight = 3
#
# [[Languages.en.menu.main]]
# name = "Service"
# URL = "service"
# weight = 4
#
# [[Languages.en.menu.main]]
# name = "Blog"
# URL = "blog"
# weight = 5
#
# [[Languages.en.menu.main]]
# weight = 6
# name = "Pages"
# hasChildren = true
#
#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "FAQ"
#   URL = "faq"
#
#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "Pricing"
#   URL = "pricing"
#
# [[Languages.en.menu.main]]
# name = "Contact"
# URL = "contact"
# weight = 7
#
#
# # footer menu
# [[Languages.en.menu.footer]]
# name = "About"
# URL = "about"
# weight = 1
#
# [[Languages.en.menu.footer]]
# name = "Project"
# URL = "project"
# weight = 2
#
# [[Languages.en.menu.footer]]
# name = "Service"
# URL = "service"
# weight = 3
#
# [[Languages.en.menu.footer]]
# name = "Pricing"
# URL = "pricing"
# weight = 4
#
# [[Languages.en.menu.footer]]
# name = "FAQ"
# URL = "faq"
# weight = 5
#
# [[Languages.en.menu.footer]]
# name = "Contact"
# URL = "contact"
# weight = 6
